version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1234
      POSTGRES_DB: laravel
    volumes:
      - ./data:/var/lib/postgresql/data
